export const ICON_LABELS = {
	AlarmClockPlus:        'Réveil +',
	Apple:                 'Apple',
	ArrowLeft:             'Flèche gauche',
	ArrowRight:            'Flèche droite',
	ArrowUpRight:          'Flèche haut-droite',
	Briefcase:             'Professionnel',
	Calendar:              'Calendrier',
	ChevronDown:           'Chevron bas',
	ChevronLeft:           'Chevron gauche',
	ChevronRight:          'Chevron droite',
	Clock:                 'Horloge',
	Code:                  'Code',
	Coffee:                'Café',
	Database:              'Base de données',
	Download:              'Télécharger',
	Globe:                 'Site web',
	GraduationCap:         'Diplôme',
	Handshake:             'Partenariat',
	HardDriveDownload:     'Sauvegarder',
	Headphones:            'Support',
	Heart:                 'Favori',
	Home:                  'Accueil',
	Key:                   'Clé',
	Leaf:                  'Feuille',
	Lock:                  'Cadenas',
	Mail:                  'E-mail',
	Map:                   'Carte',
	MapPin:                'Localisation',
	MessageCirclePlus:     'Message +',
	Microscope:            'Recherche',
	Moon:                  'Lune',
	MoveRight:             'Aller à droite',
	MoveUpRight:           'Aller en haut-droite',
	Pen:                   'Rédiger',
	PenTool:               'Stylet',
	Phone:                 'Téléphone',
	Plane:                 'Avion',
	Rocket:                'Fusée',
	Search:                'Rechercher',
	Send:                  'Envoyer',
	Server:                'Serveur',
	Settings:              'Paramètres',
	Shield:                'Sécurité',
	ShieldCheck:           'Sécurité validée',
	ShoppingBag:           'Shopping',
	Sparkles:              'Étincelles',
	SquareArrowOutUpRight: 'Lien vers',
	Star:                  'Étoile',
	Sun:                   'Soleil',
	TriangleAlert:         'Alerte',
	Upload:                'Téléverser',
	User:                  'Utilisateur',
};

export function camelToWords( name ) {
	return name.replace( /(?<!^)([A-Z])/g, ' $1' );
}
